### ISSUE TITLE
On results screen, add full emoji legend below Share this and Ask another buttons

### ISSUE THREAD

**Issue by mstem** [BadIdeaFactory/the-emoji-compass#24]
- We could display the entire final answer as a layer over the compass to give us more space to work with
- Display the final answer with the three selected emoji definitions
- document.write(symbols) immediately underneath the Ask again and Share buttons in <div class="final-text">

**Comment by louh** [comment]
we could have more room for results by having the "final" screen overlap the dial entirely? it would definitely help on mobile, where screen real estate is at a premium.

**Comment by mstem** [comment]
@louh good idea
