### ISSUE TITLE
compass emojis as big as possible

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#48]
"on the question screen with the full compass, try bumping up the size of the emojis a tiny bit… they might overlap into each other’s “zones” a little but as long as they don’t touch let’s see how big we can get them"

**Comment by margoyle** [comment]
very nice!!

**Comment by louh** [comment]
Resolved in de9e0b711a497393cd08ebcb81e7b612cb033325
