### ISSUE TITLE
make answer page start with random answer emoji highlighted

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#51]
Hopefully will help make the interaction pattern of selecting the emojis more clear to first-time users. 

<img width="382" alt="screen shot 2018-10-25 at 10 16 58 pm" src="https://user-images.githubusercontent.com/6528572/47608825-f8469d80-da01-11e8-816a-064416c2960b.png">

**Comment by louh** [comment]
Dependent on resolving #44
