### ISSUE TITLE
fix bug where descriptions don't match selected emoji in answer screen

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#53]
<img width="362" alt="screen shot 2018-10-27 at 4 13 33 pm" src="https://user-images.githubusercontent.com/6528572/47608898-4b6d2000-da03-11e8-9428-bcb20817b996.png">
<img width="355" alt="screen shot 2018-10-27 at 4 13 40 pm" src="https://user-images.githubusercontent.com/6528572/47608901-52942e00-da03-11e8-8db8-1e493059a11c.png">

**Comment by louh** [comment]
This was happening because the elements for those hitboxes in the SVG source order did not match the visual display order (left to right).
