### ISSUE TITLE
design info overlay & icon

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#59]

**Comment by margoyle** [comment]
an explanation?
biffud logo?
a link to biffud website
maybe an affiliate link to the golden compass on amazon
link to privacy policy

**Comment by mstem** [comment]
I've drafted this. Just waiting to hear people's preferred titles and to set up Amazon account plus draft privacy policy. But we should get the container that'll display the copy into place in the meantime.
