### ISSUE TITLE
Help users know what to do first by drawing attention to first needle

### ISSUE THREAD

**Issue by mstem** [BadIdeaFactory/the-emoji-compass#62]
After watching ~5 people interact with the compass, a common trip-up is knowing what to do first when they look at the app. We could help users through this moment by drawing more attention to the first needle. So instead of just making it a slightly different color, that needle could gently pulse, or shimmer, or shift colors

**Comment by margoyle** [comment]
or wiggle/tremor. snatch that NYT election needle script

**Comment by margoyle** [comment]
covered by #72
