### ISSUE TITLE
add info icon and info overlay

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#65]
<img width="791" alt="screen shot 2018-12-09 at 9 19 04 am" src="https://user-images.githubusercontent.com/6528572/49700098-4c6ba280-fba8-11e8-9488-b133e8e0b43e.png">

Text: https://docs.google.com/document/d/1fWP7-taSDII9Mnxbc7eILS4Kwg9IIdKa796TBZQ8aHo/edit

info background is white, corners are rounded at 4px
scroll bar: #C49D4F
text: #282623
Text is Gentium Book Basic regular, not bold. Line-height is ~1.3. Text can be a little larger than appears in the screen shots - realized this is too small on a phone. 
compass illustration is src/img/mini_compass.svg

info icon is 29x29 pixels (please also constrain the close icon and share icon to match). Arcs will need to be bumped down to make room for the info icon. See invision for final layout guidance https://projects.invisionapp.com/d/main#/projects/prototypes/15159709

**Comment by louh** [comment]
I think everything here is done, with remaining tasks in follow up issues #66 and #68.
