### ISSUE TITLE
About/More Info overlay screen edits

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#69]
1. Replace amazon link (and "rainforest themed website" text @mstem) with either link to library search or IndieBound - https://www.indiebound.org/book/9780440238133

2. Add explanatory paragraph to the top (above the first paragraph "The Emoji Compass is a production of Bad Idea Factory...)
>>> The Emoji Compass will tell you the answer to any question you hold in your heart. You can ask it an unlimited number of questions by combining the three emoji symbols that best represent your query. After you choose, the fourth needle will spin and hover on three more symbols, each imbued with many layers of meaning. Only by skillfully divining these meanings within will you navigate to the answer you seek.

**Comment by louh** [comment]
Updated. I also propose that we break up the text with headings, like this:

What do y'all think?

![localhost_3000_(Galaxy S5)](https://user-images.githubusercontent.com/2553268/58060348-02b3ba80-7b3f-11e9-818b-6632801bd68a.png)
![localhost_3000_(Galaxy S5) (1)](https://user-images.githubusercontent.com/2553268/58060347-02b3ba80-7b3f-11e9-8d83-2024ba43882b.png)
![localhost_3000_(Galaxy S5) (2)](https://user-images.githubusercontent.com/2553268/58060349-02b3ba80-7b3f-11e9-86ba-4e78a8c68bc5.png)

**Comment by margoyle** [comment]
I know this is already closed but I love it! @louh
