### ISSUE TITLE
Change About/More Info icon location

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#70]
Margo to design and then Lou to implement

**Comment by margoyle** [comment]
<img width="708" alt="Screen Shot 2019-05-19 at 7 25 17 PM" src="https://user-images.githubusercontent.com/6528572/57989787-07f50480-7a6e-11e9-8500-be815858350a.png">

**Comment by louh** [comment]
@margoyle Just to clarify, on the left screen (while picking emoji from the compass) we currently show the three lines of text alongside a larger version of the emoji. Are we removing that emoji?

**Comment by margoyle** [comment]
Wrote about this in the slack but yes and potential solution:
![02 04 question copy](https://user-images.githubusercontent.com/6528572/58520786-7a10cc00-8187-11e9-9160-c3370f345b2c.png)

**Comment by louh** [comment]
Ok, this should be done.
