### ISSUE TITLE
Replace about page close icon with new version

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#71]
icons = close, share, and more info

**Comment by margoyle** [comment]
So I remade the icons last weekend but the I realized that it's probably just the close icon on the about page that looks fuzzy because of the light borders, which work on the darker backgrounds, so I made a version called close_light_old.svg (img>in-app icons june19) with reversed light icon-dark border. I'm going to rename this issue and assign @louh 
<img width="308" alt="Screen Shot 2019-06-16 at 12 05 34 PM" src="https://user-images.githubusercontent.com/6528572/59566508-3941ff80-902f-11e9-8b65-eabc7154ddfc.png">

**Comment by louh** [comment]
Ok, I understand the problem and the proposed solution, but I hope I'm getting this right. There's a new folder with a bunch of new assets in it, but the only one I should be concerned with is `close_light_old.svg`, right?

**Comment by louh** [comment]
Are any of the other icons updated, as well?

**Comment by louh** [comment]
Resolved in 9ec03558a94f09ae2d0245c4a88c2c563460de9f.
