### ISSUE TITLE
Call-to-action color investigation

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#73]
Is there a color (like green on github) that can indicate interactivity/a call-to-action for the user? 
Would be applicable to:
- Active compass hand
- Share/close/more info icons
- selected emoji in answer screen

**Comment by margoyle** [comment]
I don't think a color is the right solution here. 
See some experiments below:

![colors](https://user-images.githubusercontent.com/6528572/59567088-eff5ae00-9036-11e9-9cf7-f1bffd298472.png)

**Comment by margoyle** [comment]
Red is the best but I don't think it will solve our problem. 
<img width="577" alt="Screen Shot 2019-06-16 at 1 03 48 PM" src="https://user-images.githubusercontent.com/6528572/59567108-3945fd80-9037-11e9-9a6e-830496edac9d.png">

**Comment by mstem** [comment]
Red is best! Is this in lieu of other visual effects, like pulse / shimmer
/ shimmy?

**Comment by margoyle** [comment]
I think so - we could combine them but personally I'm not feeling bringing in a color, the screens are already pretty visually rich bordering on chaotic. I just uploaded some glowing/pulsing stuff to #74, check it out

**Comment by louh** [comment]
Conversation is superceded by #74
