### ISSUE TITLE
edit emoji meanings so they are all three lines

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#76]
Don't think we came to a conclusion on this. Arguments in favor are that 1) it is a little confusing why some should have more lines than others and 2) it will simplify some layout/design issues.

**Comment by margoyle** [comment]
I realized some are two lines, I think this is okay? or if we want them to be all three lines I'm happy to help.

**Comment by slifty** [comment]
@louh I believe this is done; please re-open if that is not the case.
