### ISSUE TITLE
emoji meaning line separators 

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#77]
This symbol: 
⁓
U+2053 Swung Dash

size ~14 (rest of text should be size ~18)
<img width="708" alt="Screen Shot 2019-05-19 at 7 25 17 PM" src="https://user-images.githubusercontent.com/6528572/57989737-61a8ff00-7a6d-11e9-84a0-ab73401a987b.png">

**Comment by louh** [comment]
Resolved in 5715c4122477bf11d9fbb7250a75e0e252bf09a2
