### ISSUE TITLE
Add privacy policy to iOS app metadata

### ISSUE THREAD

**Issue by mstem** [BadIdeaFactory/the-emoji-compass#83]
We have a privacy policy and may still need to add it to the iOS App Store metadata and link it somewhere in the app

**Comment by slifty** [comment]
I link to [this privacy policy](https://github.com/BadIdeaFactory/the-emoji-compass/blob/master/PRIVACY.md) both in the app and on the app store; we can update its content to reflect the privacy policy you're referencing (we should probably use the privacy policy as a chance to have some fun too!)

**Comment by slifty** [comment]
Closing this since as written it is resolved; however we can easily tweak / update the privacy policy.  Just spin up the issue with the content you want in there and I'll push the fix.
