### ISSUE TITLE
App is draggable, make it undraggable?

### ISSUE THREAD

**Issue by margoyle** [BadIdeaFactory/the-emoji-compass#91]
![IMG_9141](https://user-images.githubusercontent.com/6528572/68324701-e88e7a00-0095-11ea-8643-4b74efc052c8.PNG)

**Comment by louh** [comment]
By draggable: Do you mean that the screen "overscrolls" when you perform a finger touch drag movement?

**Comment by margoyle** [comment]
yes I think that is what I mean
